config/routes.rb
Rails.application.routes.draw do
  get 'errors/not_found'
  get 'errors/internal_server_error'
  devise_for :users
  root to: 'pages#home'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

  resources :profils, only: [:show]
  resources :reviews, only: [:new, :create]

  resources :rentals, except: [:new, :create]
  resources :statues do
    resources :reviews
    resources :rentals, only: [:new, :create]
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/rental.rb
class Rental < ApplicationRecord
  belongs_to :user
  belongs_to :statue
end

app/models/review.rb
class Review < ApplicationRecord
  belongs_to :user
  belongs_to :statue

  validates :content, presence: true
  validates :stars, presence: true, inclusion: { in: [0, 1, 2, 3, 4, 5] }
end

app/models/statue.rb
class Statue < ApplicationRecord
  belongs_to :user

  has_many :reviews, dependent: :destroy
  has_many :rentals, dependent: :destroy

  mount_uploader :photo, PhotoUploader

  validates :name, presence: true
  validates :price, presence: true
  validates :category, presence: true
  validates :description, presence: true

  validates :material, presence: true
  validates :length, presence: true
  validates :width, presence: true
  validates :height, presence: true
  validates :location, presence: true

  geocoded_by :location
  after_validation :geocode, if: :will_save_change_to_location?


  def statue_reviews
    @statue_reviews_all = self.reviews
  end

  def statue_average
    av_rating = 0
    unless statue_reviews == []
      statue_reviews.each do |review|
        av_rating += review.stars
      end
      av_rating /= statue_reviews.length
      return av_rating
    else
      return 0
    end
  end
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
  has_many :reviews, dependent: :destroy
  has_many :rentals, dependent: :destroy
  has_many :statues, dependent: :destroy

  validates :username, presence: true, uniqueness: true
  validates :email, presence: true, uniqueness: true

  def my_statues_reviews
    user_statues = self.statues
    return user_statues.map { |statue| statue.reviews }.flatten
  end

  def avarage_rating
    av_rating = 0
    unless my_statues_reviews == []
      my_statues_reviews.each do |review|
        av_rating += review.stars
      end
      av_rating /= my_statues_reviews.length
      return av_rating
    else
      return 0
    end
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :authenticate_user!
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  skip_before_action :authenticate_user!, only: :home

  def home
    @statues = Statue.all.order(created_at: :desc).limit(6)
    @markers = @statues.map do |statue|
      {
        lat: statue.latitude,
        lng: statue.longitude,
        image_url: helpers.asset_url('pin2.png'),
        infoWindow: render_to_string(partial: "statues/info_window", locals: { statue: statue })
      }
    end
  end
end

app/controllers/profils_controller.rb
class ProfilsController < ApplicationController

  def show
    @user = User.find(params[:id])
  end
end

app/controllers/rentals_controller.rb
class RentalsController < ApplicationController
  def show
    @rental = Rental.find(params[:id])
  end

  def new
    @rental = Rental.new
    @statue = Statue.find(params[:statue_id])

    @rentals = @statue.rentals
    @rentals_dates = @rentals.map do |rental|
      {
        from: rental.start_date,
        to:   rental.end_date
      }
    end
  end

  def index
    @rentals = Rental.all
  end

  def create
    @rental        = Rental.new(rentals_params)
    @statue        = Statue.find(params[:statue_id])
    @rental.user   = current_user
    @rental.statue = @statue
    if @rental.save
      redirect_to profil_path(current_user)
    else
      render :new
    end
  end

  def destroy
    @rental = Rental.find(params[:id])
    @rental.destroy
    redirect_to user_path
  end

  private

  def rentals_params
    params.require(:rental).permit(:start_date, :end_date, :description)
  end
end

app/controllers/review_controller.rb
class ReviewController < ApplicationController

  def index
    @reviews = Review.all(params[:statue_id])
  end

  def new
    @statue = Statue.find(params[:statue_id])
    @review = Review.new
  end

  def create
    @statue = Statue.find(params[:statue_id])
    @review = Review.new(review_params)
    if @review.save
      redirect_to statue_reviews_path(@statue)
    else
      flash[:alert] = "Something went wrong."
      render :new
    end
  end

  def edit
    @review = Review.find(params[:id])
  end

  def update
    @review = Review.find(params[:id])
    @review.update(review_params)
    if @review.save
      redirect_to statue_reviews_path(@statue)
    else
      render :new
    end
  end

  def destroy
    @review = Review.find(params[:id])
    @review.destroy
  end

  private

  def review_params
    params.require(:review).permit(:content, :stars)
  end
end

app/controllers/reviews_controller.rb
class ReviewsController < ApplicationController

  # def index
  #   @reviews = Review.all
  # end

  def new
    @statue = Statue.find(params[:statue_id])
    @review = Review.new
  end

  def create
    @statue = Statue.find(params[:statue_id])
    @review = Review.new(review_params)
    @review.user = current_user
    @review.statue = @statue
    if @review.save
      redirect_to statue_path(@statue)
    else
      flash[:alert] = "Something went wrong."
      render :new
    end
  end

  def edit
    @review = Review.find(params[:id])
  end

  def update
    @review = Review.find(params[:id])
    @review.update(review_params)
    if @review.save
      redirect_to statue_reviews_path(@statue)
    else
      render :new
    end
  end

  def destroy
    @review = Review.find(params[:id])
    @review.destroy
  end

  private

  def review_params
    params.require(:review).permit(:content, :stars)
  end
end

app/controllers/statues_controller.rb
class StatuesController < ApplicationController
  skip_before_action :authenticate_user!, only: [:show, :index]

  def show
    @statue = Statue.find(params[:id])
    @markers = [{
      lat: @statue.latitude,
      lng: @statue.longitude,
      image_url: helpers.asset_url('pin2.png')
    }]
  end

  def new
    @statue = Statue.new
  end

  def index
    if params[:search].present?
      # ILIKE ==> Insensible a la casse
      # LIKE ==> Sensible a la casse
      @statues = Statue.where("name || location || material || category ILIKE ?", "%#{params[:search]}%")
    else
      @statues = Statue.geocoded
    end
    # returns statues with coordinates
    @markers = @statues.map do |statue|
      {
        lat: statue.latitude,
        lng: statue.longitude,
        image_url: helpers.asset_url('pin2.png'),
        infoWindow: render_to_string(partial: "info_window", locals: { statue: statue })
      }
    end
  end

  def create
    @statue = Statue.new(statues_params)
    @statue.user = current_user
    if @statue.save!
      redirect_to statue_path(@statue)
    else
      render :new
    end
  end

  def edit
    @statue = Statue.find(params[:id])
  end

  def update
    @statue = Statue.find(params[:id])
    @statue.update(statues_params)
    if @statue.save
      redirect_to statue_path(@statue)
    else
      render :new
    end
  end

  def destroy
    @statue = Statue.find(params[:id])
    if @statue.destroy
      redirect_to statues_path
    else
      render :edit
    end
  end

  # TENTATIVE DE PIERRE DE FAIRE FONCTIONNER LA SEARCHBAR.

  def search
    if params[:search].blank?
      redirect_to(statues_path, alert: "Empty field!") && return

    else

    @parameter = params[:id].downcase
    @results = Statues.all.where("lower(name) LIKE :search", search: @parameter)
    end
  end

  #--------------------------------------------------------------------------

  private

  def statues_params
    params.require(:statue).permit(:name, :category, :length, :width, :height, :surface, :location, :material, :description, :price, :photo, :photo_cache)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1">
    <link href="https://fonts.googleapis.com/css?family=Alata&display=swap" rel="stylesheet">
    <!-- <link href='https://api.tiles.mapbox.com/mapbox-gl-js/v1.2.1/mapbox-gl.css' rel='stylesheet' /> -->

    <title>Greet statues</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <%= action_cable_meta_tag %>
    <%= stylesheet_link_tag 'application', media: 'all' %>
    <%= stylesheet_pack_tag 'application', media: 'all' %>
  </head>

  <header><%= render 'components/navbar' %></header>
  <body>
    <p class="notice"><%= notice %></p>
    <p class="alert flash flash-warning alert-dismissible fade <%= alert.nil? ? '' : 'show' %>" role="alert"><%= alert %></p>

    <%= yield %>
        <div class="footer"><%= render 'components/footer' %></div>

    <%= javascript_include_tag 'application' %>
    <%= javascript_pack_tag 'application' %>
  </body>


</html>

app/views/pages/home.html.erb
<%= render 'components/banner' %>

<div class="container-fluid text-center">
  <div class="columns d-flex justify-content-around mt-5 mb-5">
    <div class="column p-2">
      <i class="fas fa-mobile-alt"></i><br>
      Je dépose une annonce <br>sur le site <strong>7j/7 - 24h/24</strong>.
    </div>
    <div class="column p-2">
      <i class="fas fa-check"></i><br>
      Je trouve ma statue parmi <br><strong>des milliers de propositions !</strong>
      </div>
    <div class="column p-2">
      <i class="fas fa-comment"></i><br>
      Je donne <strong>mon avis </strong><br>sur ma location.
    </div>
  </div>
</div>
<div class="container">
  <div class="row title mt-4 mb-3 d-flex align-middle">
    <i class="far fa-eye"></i> Découvrez les dernières statues en ligne
  </div>
  <div class="row">
    <% @statues.each do |statue| %>
      <div class="col-xs-12 col-md-6">
        <%= render 'components/card', statue: statue %>
      </div>
    <% end %>
  </div>
  <div class="maping" style="margin-bottom: 12px;">
    <%= render 'components/map', markers: @markers, statues: @statues %>
  </div>
</div>

<div class="container">
  <div class="container-down text-center flex-wrap mb-4">
    <div class ="friends-title mt-5 mb-5">
      <h2> <i class="far fa-handshake"></i>  Ils nous font confiance</h2></div>
    </div>
    <div class="col-md-12 d-flex justify-content-center mb-4 ">
      <div class="bd-placeholder-img bd-placeholder-img-lg img-fluid">
        <img src="http://jiajuanli.eu/wp-content/uploads/2017/04/Louvre-LOGO.png" class="friend-logo">
      </div>
      <div class="bd-placeholder-img bd-placeholder-img-lg img-fluid">
        <img src="https://upload.wikimedia.org/wikipedia/commons/thumb/7/73/The_Metropolitan_Museum_of_Art_Logo.svg/1200px-The_Metropolitan_Museum_of_Art_Logo.svg.png" class="friend-logo">
        </div>
      <div class="bd-placeholder-img bd-placeholder-img-lg img-fluid">
        <img src="https://upload.wikimedia.org/wikipedia/fr/4/46/Gr%C3%A9vin_Paris_%28logo%29.png" class="friend-logo">
      </div>
      <div class="bd-placeholder-img bd-placeholder-img-lg img-fluid">
        <img src="https://enabla.fr/wp-content/uploads/2018/12/logo-airbnb.png" class="friend-logo">
      </div>
      <div class="bd-placeholder-img bd-placeholder-img-lg img-fluid">
        <img src="https://dwj199mwkel52.cloudfront.net/assets/lewagon-logo-square-fe76916e1b923ade71e253ae6dc031d936e5e8eebac4e26b0fbac650ea6ee360.png" class="friend-logo">
      </div>
    </div>
</div>

app/views/profils/show.html.erb
<div class="container-profile d-flex justify-content-around py-4">
  <div class="contact">
    <div class="avatar-profile my-4 mx-4">
      <i class="fa fa-user-circle"></i>
      <p><%= link_to " Modifier la photo de profil", "#", class: "link_to"  %></p>
      <div class="stars-rating">
        <% @user.avarage_rating.times do %>
          <i class="fas fa-star"></i>
        <% end %>
        <% (5 - @user.avarage_rating.to_i).times do %>
          <i class="far fa-star"></i>
        <% end %>
      </div>
    </div>
    <div class="infos-profile my-4 mx-4">
      <h4><%= @user.username %></h4>
      <p>📫<%=  @user.email %></p>
      <p>📞06.37.71.29.09</p>
    </div>
    <div class="reviews-profile my-4 mx-4">
      <h3>Avis sur vous :</h3>
      <% @user.my_statues_reviews.each do |review| %>
        <div class="my-reviews">
          <div>
            <% review.stars.to_i.times do  %>
             <i class="fas fa-star"></i>
            <% end %>
            <% (5 - review.stars).times do %></%>
             <i class="far fa-star"></i>
            <% end %>
          </div>
          <p>"<%= review.content %> " by <strong><%= review.user.username %></strong></p>
        </div>
      <% end %>
    </div>
  </div>
  <div class="previous-rentals-profile">
    <h1 class="welcome-text-profile my-4 mx-4">Bonjour <%= @user.username %></h1>
    <div class="description-profile d-flex justify-content-end my-4 mx-4"><p><%= link_to " Modifier le profil", "#", class: "link_to"  %></p></div>
    <h3> Vos annonces en ligne :</h3>
    <div class="my-rentals-profile d-flex flex-wrap mb-3 py-4 my-4 mx-4">
      <% @user.statues.each do |statue| %>
        <div class="col-xs-12 col-md-6">
          <%= render 'components/card', statue: statue %>
        </div>
      <% end %>
    </div>
    <h3> Vos anciennes reservations :</h3>
    <div class="my-rentals-profile d-flex flex-wrap mb-3 py-4 my-4 mx-4">
        <% @user.rentals.each do |rental| %>
          <div class="col-xs-12 col-md-6">
            <%= render 'components/card', statue: rental.statue %>
          </div>
        <% end %>
    </div>
  </div>
</div>

app/views/rentals/_form-rental.html.erb
<div id="new_rental" data-rentals="<%= @rentals_dates.to_json %>"
></div>

  <%= simple_form_for [@statue, @rental] do |f| %>
    <%= f.input :start_date, label: 'Début de location', as: :string, required: false, input_html: {id: "range_start"} %>
    <%= f.input :end_date, label: 'Fin de location',   as: :string, required: false, input_html: {id: "range_end"} %>
    <%= f.input :description, label: 'Contacter le propriétaire' %>

    <div id="total-price" class="price d-none">
      <p>Bookez le sur ces dates pour : <br>
      <span id = "result"></span><span>€</span>
      </p>
    </div>

<!--     <div id="total-price" class="price">
      <div >Hi there</div>
      <p>Bookez le sur ces dates pour : <br>
      <span id = "result"></span><span>€</span>
      </p>
    </div> -->

    <%= f.submit 'Je réserve!', class: 'btn btn-primary' %>
    <%= link_to 'Accueil', root_path, class:'btn btn-outline-primary' %>
  <% end %>

app/views/rentals/new.html.erb
<div class="container">
  <div class="row d-flex">
    <div class="show-card mr-3">
      <div class="title mb-2">
        Bookez <%= @statue.name %> avant <br>qu'il ne soit trop tard!
      </div>
      <%= render 'form-rental' %>
    </div>
    <div class="show-card col-xs-12 col-lg-6">
      <div class="title mb-3"><%= @statue.name %> vous attend!</div>
      <div id="price" class='d.none' data-price="<%= @statue.price %>"></div>
      <%= cl_image_tag @statue.photo, class: 'show_img_rental' %>
    </div>
  </div>
</div>

app/views/reviews/new.html.erb
<%= render "components/stars_ratings" %>

app/views/statues/_form.html.erb
<div class="cover">
  <div class="container-form">
    <h1> GAGNEZ DE L'ARGENT EN LOUANT VOTRE STATUE !</h1>

    <%= simple_form_for @statue do |f| %>
      <div class="tab first active">
        <div class="title mb-3">
          Décrivez-nous votre statue:
        </div>
        <%= f.input :name,        label: 'Nom de la statue', placeholder: 'Aphrodite', class: "input"%>
        <%= f.input :description, placeholder: "Décrivez votre statue en quelques mots. Donnez envie ! 🗿", class: "text-area my-5 text-uppercase" %>
      </div>
      <div class="tab d-none second">
        <div class="title mb-3">
          Quelques petites infos pour mieux vous référencer :
        </div>
        <%= f.input :category, label: 'Catégorie', class: "input", collection: ["Bas relief", "Sculpture Equestre", "Buste", "Sculpture monumentale", "Sculpture antique", "Art contemporain", "Art nouveau", "Rococo", "Art baroque", "Nain de jardin", "Décoration de Noël", "Romanesque", "Sculpture sur bois", "Bronze"].sort %>
        <%= f.input :length,   label: 'Longueur', placeholder: "cm", class: "input" %>
        <%= f.input :width,    label: 'Largeur', placeholder: "cm",class: "input" %>
        <%= f.input :height,   label: 'Hauteur', placeholder: "cm",class: "input" %>
        <%= f.input :material, label: 'Matière', class: "input", collection: ["Plastique", "Bois", "Bronze", "Acier", "Aluminium", "Papier", "Granit", "Pierre", "Marbre"].sort %>
      </div>
      <div class="tab d-none step-before-last">
        <div class="title mb-3">
          Où la mettez vous à disposition :
        </div>
        <%= f.input :location, label: 'Ville', placeholder: "Paris",class: "input" %>
      </div>
      <div class="tab d-none">
        <div class="title mb-3">
          Votre prix sera le notre!
        </div>
        <%= f.input :price,     label: 'Tarif journalier - (nos experts en art vérifieront.)', input_html: { min: '0'}, placeholder: "Make it rain!" %>
        <p>📸 </p>
        <%= f.input :photo,     label:"Une photo vaut mieux que 1000 mots!", class: "input-poto" %>
        <%= f.input :photo_cache, as: :hidden %>

        <%= f.button :submit, class: "btn-flat" %>
      </div>

      <div id="buttons" style="overflow:auto;">
        <div class="buttons_form">
          <div id="prev-btn" class="btn btn-flat d-none">Previous</div>
          <div id="next-btn" class="btn btn-flat">Next</div>
        </div>
      </div>

    <% end %>
    <!-- <div class="flash flash-success alert alert-dismissible fade show" role="alert">
      <span><strong>Yay!</strong> 🎉 you successfully added a statue.</span>
      <a data-dismiss="alert" aria-label="Close">
        <i class="fas fa-times"></i>
      </a>
      input-poto
    </div> -->
  </div>
</div>

app/views/statues/_info_statue.html.erb
<h2><%= statue.name %></h2>
<p><%= statue.price %></p>

app/views/statues/_info_window.html.erb
<h2><%= statue.name %></h2>
<p><%= 'Ville : ' + statue.location %></p>
<p><%= 'Propriétaire : ' + statue.user.username %></p>
<a><%= cl_image_tag statue.photo %></a>

app/views/statues/edit.html.erb
<div class="cover">
  <div class="container-form">
    <h1> Faites les modifications de votre statue ici :</h1>

    <%= simple_form_for @statue do |f| %>

      <%= f.input :name,     label: 'Nom de la statue', placeholder: 'Aphrodite', class: "input"%>
      <%= f.input :category, label: 'Catégorie', class: "input", collection: ["Bas relief", "Sculpture Equestre", "Buste", "Sculpture monumentale", "Sculpture antique", "Art contemporain", "Art nouveau", "Rococo", "Art baroque", "Nain de jardin", "Décoration de Noël", "Romanesque", "Sculpture sur bois", "Bronze"].sort %>
      <%= f.input :length,   label: 'Longueur', placeholder: "cm", class: "input" %>
      <%= f.input :width,    label: 'Largeur', placeholder: "cm",class: "input" %>
      <%= f.input :height,   label: 'Hauteur', placeholder: "cm",class: "input" %>
      <%= f.input :surface,  placeholder: "cm",class: "input" %>
      <%= f.input :location, label: 'Ville', placeholder: "Paris",class: "input" %>
      <%= f.input :material, label: 'Matière', class: "input", collection: ["Plastique", "Bois", "Bronze", "Acier", "Aluminium", "Papier", "Granit", "Pierre", "Marbre"].sort %>
      <%= f.input :description, placeholder: "Décrivez votre statue en quelques mots. Donnez envie ! 🗿", class: "text-area my-5 text-uppercase" %>
      <%= f.input :price,    label: 'Tarif journalier - (nos experts en art vérifieront.)', input_html: { min: '0'}, placeholder: "Make it rain!" %>
      <p>📸 </p>
      <%= f.input :photo, label:"Une photo vaut mieux que 1000 mots!", class: "btn btn-ghost" %>
      <%= f.input :photo_cache, as: :hidden %>
      <%= f.button :submit, class: "btn-flat" %>
      <p class="btn-delete"><%= link_to "Supprimer votre statue", statue_path(@statue), method: :delete  %></p>
    <% end %>
    <!-- <div class="flash flash-success alert alert-dismissible fade show" role="alert">
      <span><strong>Yay!</strong> 🎉 you successfully added a statue.</span>
      <a data-dismiss="alert" aria-label="Close">
        <i class="fas fa-times"></i>
      </a>
    </div> -->
  </div>
</div>

app/views/statues/index.html.erb
<div class="container">
  <div class="row">

    <% @statues.each do |statue| %>

      <div class="col-xs-12 col-md-6">
        <%= render 'components/card', statue: statue %>
      </div>
    <% end %>
  </div>

  <div
  id="map"
  style="width: 100%;
  height: 600px;"
  data-markers="<%= @markers.to_json %>"
  data-mapbox-api-key="<%= ENV['MAPBOX_API_KEY'] %>"
  ></div>
</div>

app/views/statues/new.html.erb
<%= render "form" %>

app/views/statues/show.html.erb
<div class="container">
  <div class="row d-flex">
    <div class="show-card mr-3">
      <ul>
        <li>
          <h1><i class="fas fa-star"></i><%= @statue.name.upcase %></h1>
          <h3><%= @statue.category %></h3>
          <em><%= @statue.description.capitalize %></em>
          <h2><%= @statue.price.to_s + " €/J"%></h2><br>
          <%= cl_image_tag @statue.photo, :class => "show_img", height: 300, width: 400, crop: :fill %>
          <div class="card-details d-flex flex-column justify-content-between">
          <div class="item">
            <i class="fas fa-map-marked-alt"></i><%= ' Adresse :' + ' ' + @statue.location %><br>
          </div>
          <div class="item">
            <i class="fas fa-gem"></i><%= ' Matière :' + ' ' + @statue.material %><br>
          </div>
          <div class="item">
            <i class="fas fa-arrows-alt-v"></i><%= ' Hauteur :' + ' ' + @statue.height.to_s + ' cm' %><br>
          </div>
          <div class="item">
            <i class="fas fa-arrows-alt-h"></i><%= ' Largeur :' + ' ' + @statue.width.to_s + ' cm' %><br>
          </div>
          <div class="item">
            <i class="fas fa-ruler"></i><%= ' Profondeur :' + ' ' + @statue.length.to_s + ' cm' %><br>
          </div>
          <div class="item">
            <i class="fas fa-expand-arrows-alt"></i><%= ' Surface à prévoir :' + ' ' + (@statue.width * @statue.length).to_s + ' cm2' %><br>
          </div>
          </div>
        </li>
      </ul>
    <div><i class="fas fa-heart"></i><%= link_to " JE VEUX LA LOUER !", new_statue_rental_path(@statue),
                    :class => "btn-reservation" %>
    </div><br>
    <div><%= link_to "Retour", statues_path,
                    :class => "btn-show-options" %>
          <%= link_to "Éditer", edit_statue_path(@statue),
                    :class => "btn-show-edit" %>
          <%= link_to "Supprimer", statue_path(@statue),
                    :class => "btn-show-delete",
                    :data => {:confirm => "ATTENTION, vous allez supprimer toutes les données de votre statue. Êtes-vous sûr(e) ?",
                             :method => "delete"} %>
    </div>
    </div>
    <div class></div>
    <div class="show-card col-xs-12 col-lg-6">
      <div class="title">
        Moyenne des avis :
      </div>
      <div class="stars-rating mb-5">
        <% @statue.statue_average.times do %>
          <i class="fas fa-star"></i>
        <% end %>
        <% (5 - @statue.statue_average.to_i).times do %>
          <i class="far fa-star"></i>
        <% end %>
      </div>
      <div class="title">Découvrez où se cache cette statue :</div>
      <%= render 'components/map', markers: @markers %>
    </div>

  </div>
</div>